# Deskwork configuration
#
# Copy this file to:
# ~/.config/deskwork/config.conf
#
# Then change the paths below.

wallpaper_dir = "/home/USER/Pictures/Deskwork_wallpapers"
cache_file = "/home/USER/.cache/deskwork/location.cache"


#NEEDS TO BE IN THE SAME DIRECTORY OF THE C FILE
